"""Platform port. All returned values are JSON data except local PIL frames.

inspect: {elements: [{native_id, role, name, value, bounds, ...}], coverage}.
target: {target_id, identity, title, geometry_id, bounds, client_origin}.
dispatch must recheck binding and foreground, never retry, and release owned
inputs on every exit. A native acknowledgement is NOT an effect verification.
"""
from typing import Protocol


class PlatformPort(Protocol):
    def capabilities(self) -> dict: ...
    def targets(self) -> list[dict]: ...
    def bind(self, target_id: str) -> dict: ...
    def release(self) -> None: ...
    def close(self) -> None: ...


class AccessibilityPort(Protocol):
    def inspect(self, target: dict, query: dict | None = None) -> dict: ...


class CapturePort(Protocol):
    def capture(self, target: dict): ...


class ObservationHandle(Protocol):
    def snapshot(self) -> dict: ...
    def close(self) -> None: ...


class TemporalCapturePort(Protocol):
    # Optional, advertised by temporal_capture. Returns a read-only handle with
    # snapshot()/close(); source independently tracks lifetime/geometry. Caller
    # must rebind the original target after arming and close before replay.
    def open_observer(self, target: dict, settings: dict, baseline: dict, deadline: float, *, cancel=None) -> ObservationHandle: ...


class OCRPort(Protocol):
    def ocr(self, target: dict, region: list[int] | None) -> dict: ...


class EventsPort(Protocol):
    def events(self, target: dict, since: int = 0) -> dict: ...


class InputPort(Protocol):
    def acquire_lease(self) -> None: ...
    def release_lease(self) -> None: ...
    def cancel(self) -> None: ...
    def cleanup_status(self) -> dict: ...
    def dispatch(self, target: dict, op: str, args: dict, timeout: float) -> dict: ...
